# Generated by Django 5.2.8 on 2025-12-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='games/'),
        ),
        migrations.AddField(
            model_name='product',
            name='lore',
            field=models.TextField(blank=True, null=True),
        ),
    ]
